services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-chatbot123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-chatbot_db}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    networks:
      - chatbot-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-chatbot123}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  chatbot:
    build: .
    container_name: chatbot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql-db:3306/chatbot_db}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-chatbot123}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      COINGECKO_API_URL: ${COINGECKO_API_URL:-https://api.coingecko.com/api/v3}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - chatbot-network
    restart: on-failure

networks:
  chatbot-network:
    driver: bridge

volumes:
  mysql_data:

